/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uabc.protsoft;

import javax.swing.ImageIcon;

/**
 *
 * @author Jonathan
 */
public class protInter extends javax.swing.JFrame {

    /**
     * Creates new form protInter
     */
    private String ruta;
    
    public protInter() {
        ruta = "src\\Imagenes\\";
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(850, 600);
        first.setIcon(generarImagen(first.getWidth(),first.getHeight(),ruta+"fm.png"));
        third.setIcon(generarImagen(first.getWidth(),first.getHeight(),ruta+"museo.png"));
        descfood.setText("Aquí va la descripción breve del lugar");
        descmus.setText("Aquí va otra descripción breve de otro lugar");
        menu();
    }
    
    public void menu(){
        first.setVisible(true);
        third.setVisible(true);
        descfood.setVisible(true);
        descmus.setVisible(true);
        verm1.setVisible(true);
        verm3.setVisible(true);
        descgran.setVisible(false);
        imagcentral.setVisible(false);
        regresar.setVisible(false);
    }
    
    public void showcase(){
        first.setVisible(false);
        third.setVisible(false);
        descfood.setVisible(false);
        descmus.setVisible(false);
        verm1.setVisible(false);
        verm3.setVisible(false);
        descgran.setVisible(true);
        imagcentral.setVisible(true);
        regresar.setVisible(true);
    }
    
    public ImageIcon generarImagen(int ancho, int alto, String nombre) {
        ImageIcon imagen = new ImageIcon(nombre);
        imagen = new ImageIcon(imagen.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH));
        return imagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backG = new javax.swing.JPanel();
        third = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        verm3 = new javax.swing.JButton();
        descmus = new javax.swing.JLabel();
        descfood = new javax.swing.JLabel();
        verm1 = new javax.swing.JButton();
        imagcentral = new javax.swing.JLabel();
        descgran = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        backG.setBackground(new java.awt.Color(255, 255, 255));
        backG.setMinimumSize(new java.awt.Dimension(800, 500));
        backG.setPreferredSize(new java.awt.Dimension(800, 500));
        backG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        third.setBackground(new java.awt.Color(255, 255, 255));
        third.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        third.setMinimumSize(new java.awt.Dimension(200, 133));
        third.setPreferredSize(new java.awt.Dimension(150, 133));
        backG.add(third, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 450, 240));

        first.setBackground(new java.awt.Color(255, 255, 255));
        first.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        first.setMinimumSize(new java.awt.Dimension(200, 133));
        first.setPreferredSize(new java.awt.Dimension(150, 133));
        backG.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 450, 250));

        verm3.setText("Ver más...");
        verm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verm3ActionPerformed(evt);
            }
        });
        backG.add(verm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        descmus.setText("jLabel1");
        descmus.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backG.add(descmus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 210));

        descfood.setText("jLabel1");
        descfood.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backG.add(descfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 190));

        verm1.setText("Ver más...");
        verm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verm1ActionPerformed(evt);
            }
        });
        backG.add(verm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));
        backG.add(imagcentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 470, 360));

        descgran.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backG.add(descgran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 380));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        backG.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verm1ActionPerformed
        // TODO add your handling code here:
        imagcentral.setIcon(generarImagen(first.getWidth(),first.getHeight(),ruta+"fm.png"));
        descgran.setText("Aquí iría la descripción más general del lugar");
        showcase();
    }//GEN-LAST:event_verm1ActionPerformed

    private void verm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verm3ActionPerformed
        // TODO add your handling code here:
        imagcentral.setIcon(generarImagen(first.getWidth(),first.getHeight(),ruta+"museo.png"));
        descgran.setText("Aquí iría la descripción más general del lugar");
        showcase();
    }//GEN-LAST:event_verm3ActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        menu();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(protInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(protInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(protInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(protInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new protInter().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backG;
    private javax.swing.JLabel descfood;
    private javax.swing.JLabel descgran;
    private javax.swing.JLabel descmus;
    private javax.swing.JLabel first;
    private javax.swing.JLabel imagcentral;
    private javax.swing.JButton regresar;
    private javax.swing.JLabel third;
    private javax.swing.JButton verm1;
    private javax.swing.JButton verm3;
    // End of variables declaration//GEN-END:variables
}
